### ISSUE TITLE
Wiki link does not open

### ISSUE THREAD

**Issue by alexxis** [ivelum/job#1]
[Wiki link](https://latacora.singles/2018/08/03/the-default-openssh.html) does not open on [page](https://github.com/ivelum/job/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BF%D0%BE-%D0%B7%D0%B0%D1%89%D0%B8%D1%82%D0%B5-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85). Browser goes to page with text: `Not Found`.

**Comment by Perlence** [comment]
Thanks, fixed!
